### ISSUE TITLE
bug: `lockTimeOut` is not working due bad value check

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/helm-charts#2]
https://github.com/repository-service-tuf/helm-charts/blob/e02e0e0592670f6d2b6f93ba5d9e288d60b7f246/charts/rstuf-worker/templates/deployment.yaml#L109-L112

```yaml
 {{- if .Values.backend.lockTimeOut }} 
 - name: RSTUF_LOCK_TIMEOUT 
   value: {{ .Values.backend.lockTimeOut | quote }} 
 {{- end }} 
```
